management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /todo/api/management
spring:
  jmx:
    enabled: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/todo_schema
    password: Mu18052007
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    serialization:
      indent-output: true
todo:
  email:
    username: todolist-official
    password: Listing28Todos
    host: imap.todo.com
    port: 143
    mailbox: INBOX
    poll-rate: 10000