management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /todo/api/management
spring:
  email:
    username: otodolist@gmail.com
    password: Listing28Todos
    host: smtp.gmail.com
    port: 143
  jmx:
    enabled: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/todo_schema
    password: Mu18052007
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    serialization:
      indent-output: true
todo:
  email:
    message:
      subject: TodoList Expiration!
      body: Hello from TodoList!%n%nYour TodoList has been expired!%nInformation about your TodoList:%n%s%n%s%n%s%n%s%n%s